In [20]:
#the first step of numpy is to tell python to use it 
import numpy as np

print(np.cos(0))
print(np.sqrt(78))

1.0
8.831760866327848


In [9]:
#we can create numpy arrays by converting list
#this is a vector

vec=np.array([1,2,3])
print(vec)
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(' ')
print(mat)
print(" ")
print(mat.T)

[1 2 3]
 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
#there are lots of methords to create numpy arrays
vec1=np.arange(1,15)
print(vec1)
vec2=np.arange(5,20,2)                   #intial,endingt,inc
print(vec2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  7  9 11 13 15 17 19]


In [18]:
vec1= np.linspace(0,2,10)
print(vec1)


[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
