In [1]:
#the first step of numpy is to tell python to use it 
import numpy as np

print(np.cos(0))
print(np.sqrt(78))

1.0
8.831760866327848


In [2]:
#we can create numpy arrays by converting list
#this is a vector

vec=np.array([1,2,3])
print(vec)
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(' ')
print(mat)
print(" ")
print(mat.T)

[1 2 3]
 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
#there are lots of methords to create numpy arrays
vec1=np.arange(1,15)
print(vec1)
vec2=np.arange(5,20,2)                   #intial,endingt,inc
print(vec2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  7  9 11 13 15 17 19]


In [4]:
vec1= np.linspace(0,2,10)
print(vec1)


[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [5]:
#We also acess the entries with logicals
rand_vec=np.random.randn(15)
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.32157909 -0.20472427  0.11481581 -0.45640281 -0.56912221  0.17322936
  1.55061777  1.38218838  0.55095129  1.1048349   0.62021845 -0.04517495
 -0.68991495  0.07893071  0.23227527]
[False False  True False False  True  True  True  True  True  True False
 False  True  True]
[0.11481581 0.17322936 1.55061777 1.38218838 0.55095129 1.1048349
 0.62021845 0.07893071 0.23227527]


In [6]:
rand_mat2=np.random.randn(30)
print(rand_mat2)
print(rand_mat2>0)
print(rand_mat2[rand_mat2>0])

[ 1.34024882  0.84904962  1.32855011 -0.71220931  0.31212744  0.31472999
  0.72029803 -0.90523895  1.32877802  0.41491578 -0.46049789  1.28075813
 -1.5003461  -0.14868679  0.00611761 -0.6693814  -1.5339865  -0.41983568
  0.11442823 -0.28937365 -1.10846544 -0.70372556 -0.61343343  0.0037796
  1.79579177 -1.90275566 -0.42218861  1.1246474   1.88311342  0.72447126]
[ True  True  True False  True  True  True False  True  True False  True
 False False  True False False False  True False False False False  True
  True False False  True  True  True]
[1.34024882 0.84904962 1.32855011 0.31212744 0.31472999 0.72029803
 1.32877802 0.41491578 1.28075813 0.00611761 0.11442823 0.0037796
 1.79579177 1.1246474  1.88311342 0.72447126]


In [7]:
list=np.array([[1,2,3],[4,5,6],[5,6,7]])
list

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [8]:
list.shape

(3, 3)

In [9]:
list.size


9

In [10]:
arr=np.arange(1,100)

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
arr.reshape(3,33)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]])

In [13]:
a=arr.ravel()

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [16]:
ar=np.array(x)

In [17]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [18]:
ar.sum(axis=0)

array([12,  8,  9])

In [19]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [20]:

ar.T          #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [21]:
ap= np.array([31,5,14,61,20])
ap

array([31,  5, 14, 61, 20])

In [22]:
ap.argmax()

3

In [23]:
ap.argmin()

1

In [24]:
ap.argsort()

array([1, 2, 4, 0, 3], dtype=int64)